version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: contactform
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
